export const DEFAULT_BLOCKS = [
  { name: "Scope", version: 0, output: {},
    hypothesis: "The subject is {}",
    labels: [
      "the speaker",
      "another person",
      "an animal",
      "an occupation",
      "an object",
      "a place",
      "something else",
    ]},
  { name: "Mode", version: 0, output: {},
    hypothesis: "This text is about {}",
    labels: [
      "people",
      "animals",
      "environments",
      "currency",
      "feelings",
      "something else",
    ]},
  { name: "Stats", version: 0, output: {},
    hypothesis: "This text is about {}",
    labels: [
      "health",
      "stamina",
      "something else",
    ]},
  { name: "Equipment", version: 0, output: {},
    hypothesis: "This text is about {}",
    labels: [
      "swords",
      "guns",
      "armor",
      "fists",
      "something else",
    ]},
  { name: "Mood", version: 0, output: {},
    hypothesis: "This behavior is usually {}",
    labels: [
      "relaxing",
      "aggresive",
      "careful",
      "happy",
      "something else",
    ]},
];
